(delete 'width initial-frame-alist)
(delete 'height initial-frame-alist)
(delete 'top initial-frame-alist)
(delete 'left initial-frame-alist)
(setq initial-frame-alist (append (list
'(width . 80)
'(height . 24)
'(top . 103)
'(left . 1934))
initial-frame-alist))
