(delete 'width initial-frame-alist)
(delete 'height initial-frame-alist)
(delete 'top initial-frame-alist)
(delete 'left initial-frame-alist)
(setq initial-frame-alist (append (list
'(width . 268)
'(height . 60)
'(top . 48)
'(left . 0))
initial-frame-alist))
